### ISSUE TITLE
ani-button não altera tamanho dinamicamente

### ISSUE THREAD

**Issue by jcorrea97** [animaliads/animalia-web-components#45]
Ao tentar alterar o ani-button para o tamanho `small` dinamicamente ocorre uma redução na largura e altura do botão, porém não com os valores esperados.

teste React :
https://stackblitz.com/edit/react-ani-button-scvvrp

Teste Angular:
html:
```
<ani-button [attr.size]="size === true ? 'small' : 'medium'">Button</ani-button>

<button (click)="muda()">muda</button>
```

ts:

```
size = false;

muda() {
    // eslint-disable-next-line no-unused-expressions
    this.size = !this.size

  }
```

A tag do `ani-button` recebe a alteração do size para `small`, porém a tag interna `button` mantém o valor do size como `medium`  :
![image](https://user-images.githubusercontent.com/57047381/152421985-4621c107-c51f-4e17-a54b-f724261acb39.png)

**Comment by rafaellmarques** [comment]
Atributo `size` foi adicionado à lista de observáveis e passa a suportar modificações para corrigir o comportamento informado.
